apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-database-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/sqlite
  storageClassName: standard