apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: api-alumnos  # Debe coincidir con el selector del Deployment
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort